/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mGbirUW5O0x
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function PodcastLandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-[#1e1e1e] text-[#d4d4d4]">
      <header className="px-4 lg:px-6 h-14 flex items-center border-b border-[#2b2b2b]">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <TerminalIcon className="h-6 w-6" />
          <span className="sr-only">The Craft of Developer Experiences Podcast</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Episodes
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex-1 px-4 lg:px-6 py-12 md:py-24 lg:py-32">
        <div className="container max-w-5xl mx-auto">
          <div className="space-y-12">
            <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter">
                  Episode 1: The Art of Crafting Delightful Developer Experiences
                </h2>
                <div className="flex items-center gap-2 text-sm text-[#9e9e9e]">
                  <UsersIcon className="h-4 w-4" />
                  <span>John Doe, Jane Smith, Alex Johnson</span>
                </div>
                <p className="text-[#d4d4d4]">
                  In this episode, we dive into the art of crafting delightful developer experiences. Our panel of
                  experts discuss the key principles, best practices, and real-world examples of building
                  developer-centric products and tools that delight and empower the end-user.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AirplayIcon className="h-4 w-4 mr-2" />
                    Spotify
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AppleIcon className="h-4 w-4 mr-2" />
                    Apple Podcasts
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Episode 1"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
            </section>
            <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Episode 2"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter">
                  Episode 2: Leveraging Design Systems for Developer Productivity
                </h2>
                <div className="flex items-center gap-2 text-sm text-[#9e9e9e]">
                  <UsersIcon className="h-4 w-4" />
                  <span>Sarah Lee, Michael Chen, Emily Wang</span>
                </div>
                <p className="text-[#d4d4d4]">
                  In this episode, our panel explores the power of design systems in boosting developer productivity.
                  They discuss how well-designed, reusable components and guidelines can streamline the development
                  process, improve consistency, and ultimately deliver better experiences for end-users.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AirplayIcon className="h-4 w-4 mr-2" />
                    Spotify
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AppleIcon className="h-4 w-4 mr-2" />
                    Apple Podcasts
                  </Link>
                </div>
              </div>
            </section>
            <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter">
                  Episode 3: Bridging the Gap: Improving Developer-Designer Collaboration
                </h2>
                <div className="flex items-center gap-2 text-sm text-[#9e9e9e]">
                  <UsersIcon className="h-4 w-4" />
                  <span>David Lee, Samantha Nguyen, Mark Gonzalez</span>
                </div>
                <p className="text-[#d4d4d4]">
                  In this episode, our panel discusses strategies for improving collaboration between developers and
                  designers. They explore effective communication techniques, shared tools and workflows, and ways to
                  foster a culture of empathy and understanding between these two crucial disciplines.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AirplayIcon className="h-4 w-4 mr-2" />
                    Spotify
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AppleIcon className="h-4 w-4 mr-2" />
                    Apple Podcasts
                  </Link>
                </div>
              </div>
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Episode 3"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
            </section>
            <section className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <img
                src="/placeholder.svg"
                width="400"
                height="300"
                alt="Episode 4"
                className="rounded-lg object-cover"
                style={{ aspectRatio: "400/300", objectFit: "cover" }}
              />
              <div className="space-y-4">
                <h2 className="text-3xl font-bold tracking-tighter">
                  Episode 4: Unleashing Developer Creativity with No-Code Tools
                </h2>
                <div className="flex items-center gap-2 text-sm text-[#9e9e9e]">
                  <UsersIcon className="h-4 w-4" />
                  <span>Jessica Huang, Tom Nguyen, Olivia Patel</span>
                </div>
                <p className="text-[#d4d4d4]">
                  In this episode, our panel explores the rise of no-code tools and how they are empowering developers
                  to be more creative and productive. They discuss the benefits, use cases, and best practices for
                  leveraging these powerful platforms to build innovative applications without the traditional barriers
                  to entry.
                </p>
                <div className="flex gap-2">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AirplayIcon className="h-4 w-4 mr-2" />
                    Spotify
                  </Link>
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#3c3c3c] px-4 py-2 text-sm font-medium text-[#d4d4d4] shadow transition-colors hover:bg-[#4c4c4c] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#2b2b2b] disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    <AppleIcon className="h-4 w-4 mr-2" />
                    Apple Podcasts
                  </Link>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t border-[#2b2b2b]">
        <p className="text-xs text-[#9e9e9e]">
          &copy; 2024 The Craft of Developer Experiences Podcast. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4 text-[#9e9e9e]" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4 text-[#9e9e9e]" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function AirplayIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1" />
      <path d="m12 15 5 6H7Z" />
    </svg>
  )
}


function AppleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function TerminalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 17 10 11 4 5" />
      <line x1="12" x2="20" y1="19" y2="19" />
    </svg>
  )
}


function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
